"""P_400 Council reason-code constants.

Imported by council.py, risk_vote.py, and their test files.
No logic here - string constants only.
"""

RC_RR_BELOW_MIN = "RR_BELOW_MIN"
RC_STOP_TOO_TIGHT = "STOP_TOO_TIGHT"
RC_STOP_BREAKS_RR = "STOP_BREAKS_RR"
RC_HEAT_BREACH = "HEAT_BREACH"
RC_POSITION_COUNT = "POSITION_COUNT"
RC_DAILY_LOSS = "DAILY_LOSS"
RC_SECTOR_CONCENTRATION = "SECTOR_CONCENTRATION"
RC_CASH_BELOW_RISK = "CASH_BELOW_RISK"
RC_EARNINGS_IN_WINDOW = "EARNINGS_IN_WINDOW"
RC_PRICE_STALE = "PRICE_STALE"
RC_ADVERSE_DRIFT = "ADVERSE_DRIFT"
RC_MARKET_CLOSED = "MARKET_CLOSED"
RC_REVENGE_TRADE = "BEHAVIORAL_REVENGE"
RC_OVERTRADING = "BEHAVIORAL_OVERTRADING"
RC_STREAK_CHASING = "BEHAVIORAL_STREAK_CHASING"
RC_POST_EARNINGS_STABILIZATION = "POST_EARNINGS_STABILIZATION"
RC_ALL_CLEAR = "ALL_CLEAR"