"""
FILE: schemas_preflight.py
VERSION: 1.0
DATE: 2026-06-18
AUTHOR: Anthony Zoppi + Claude
LAYER: schema
DESCRIPTION:
    Pydantic model for the P_300 preflight status artifact written by
    utilities/preflight_status.py and consumed by INIT Steps 5b/5c (SIP
    v3.2). Replaces live windows-mcp:PowerShell Python subprocess calls
    during INIT with a file read -- see WO-P000-E4.001.

    PreflightStatus is the single persistent-I/O contract between the
    preflight script (run by the operator via P_300_Preflight.bat,
    outside the chat session) and INIT (which reads the resulting JSON
    via windows-mcp:FileSystem).

CHANGELOG:
    - 2026-06-18 v1.0: Created for WO-P000-E4.001 (INIT execution bypass).
"""
from __future__ import annotations

from pydantic import BaseModel


class PreflightStatus(BaseModel):
    """Snapshot of catalog health + LM Studio readiness, generated by
    preflight_status.py and read by INIT instead of live subprocess calls."""

    generated_at: str  # ISO 8601, e.g. "2026-06-18T14:32:05-04:00"

    # -- Catalog health (was: cli.py catalog-summary) --
    catalog_path: str
    catalog_filename: str
    pattern_count: int
    symbol_count: int
    hollow_count: int
    catalog_overall: str  # "HEALTHY" | "ATTENTION REQUIRED" | "ERROR"
    catalog_error: str | None = None

    # -- LM Studio readiness (was: p300_status_check.py) --
    lm_studio_running: bool
    lm_studio_model: str | None = None
    lm_studio_model_mismatch: bool = False
    lm_studio_message: str = ""
    lm_studio_error: str | None = None
